// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/lotus.proto

package backend

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aace03ecbbb4cb2, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Lot struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Country              string   `protobuf:"bytes,4,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lot) Reset()         { *m = Lot{} }
func (m *Lot) String() string { return proto.CompactTextString(m) }
func (*Lot) ProtoMessage()    {}
func (*Lot) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aace03ecbbb4cb2, []int{1}
}

func (m *Lot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lot.Unmarshal(m, b)
}
func (m *Lot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lot.Marshal(b, m, deterministic)
}
func (m *Lot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lot.Merge(m, src)
}
func (m *Lot) XXX_Size() int {
	return xxx_messageInfo_Lot.Size(m)
}
func (m *Lot) XXX_DiscardUnknown() {
	xxx_messageInfo_Lot.DiscardUnknown(m)
}

var xxx_messageInfo_Lot proto.InternalMessageInfo

func (m *Lot) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Lot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lot) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Lot) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type Lots struct {
	Lots                 []*Lot   `protobuf:"bytes,1,rep,name=lots,proto3" json:"lots,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lots) Reset()         { *m = Lots{} }
func (m *Lots) String() string { return proto.CompactTextString(m) }
func (*Lots) ProtoMessage()    {}
func (*Lots) Descriptor() ([]byte, []int) {
	return fileDescriptor_2aace03ecbbb4cb2, []int{2}
}

func (m *Lots) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lots.Unmarshal(m, b)
}
func (m *Lots) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lots.Marshal(b, m, deterministic)
}
func (m *Lots) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lots.Merge(m, src)
}
func (m *Lots) XXX_Size() int {
	return xxx_messageInfo_Lots.Size(m)
}
func (m *Lots) XXX_DiscardUnknown() {
	xxx_messageInfo_Lots.DiscardUnknown(m)
}

var xxx_messageInfo_Lots proto.InternalMessageInfo

func (m *Lots) GetLots() []*Lot {
	if m != nil {
		return m.Lots
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "backend.Empty")
	proto.RegisterType((*Lot)(nil), "backend.Lot")
	proto.RegisterType((*Lots)(nil), "backend.Lots")
}

func init() { proto.RegisterFile("protos/lotus.proto", fileDescriptor_2aace03ecbbb4cb2) }

var fileDescriptor_2aace03ecbbb4cb2 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xe5, 0xd8, 0xc5, 0xe2, 0x80, 0x0e, 0x37, 0x59, 0x9d, 0xac, 0x4c, 0x9e, 0x82, 0x54,
	0x7e, 0x01, 0x10, 0x84, 0x22, 0x59, 0x0c, 0x59, 0x11, 0x43, 0x4b, 0x3c, 0xd1, 0xf6, 0xa2, 0xdc,
	0x65, 0xc8, 0xbf, 0x47, 0x38, 0x01, 0x91, 0xed, 0xbe, 0xfb, 0xde, 0xf0, 0x1e, 0x60, 0x3f, 0x90,
	0x10, 0xdf, 0x9f, 0x48, 0x46, 0xae, 0x32, 0xa0, 0x3d, 0x1e, 0x3e, 0xbf, 0xd2, 0xa5, 0x2b, 0x2d,
	0x6c, 0x5e, 0xce, 0xbd, 0x4c, 0xe5, 0x07, 0xe8, 0x48, 0x82, 0x5b, 0x28, 0x9a, 0xda, 0x29, 0xaf,
	0x82, 0x6e, 0x8b, 0xa6, 0x46, 0x04, 0xf3, 0x76, 0x38, 0x27, 0x57, 0x78, 0x15, 0xae, 0xdb, 0x7c,
	0xa3, 0x03, 0xfb, 0xd8, 0x75, 0x43, 0x62, 0x76, 0x3a, 0xbf, 0x7f, 0xf1, 0xc7, 0x3c, 0xd3, 0x78,
	0x91, 0x61, 0x72, 0x66, 0x36, 0x0b, 0x96, 0x01, 0x4c, 0x24, 0x61, 0xf4, 0x60, 0x4e, 0x24, 0xec,
	0x94, 0xd7, 0xe1, 0x66, 0x7f, 0x5b, 0x2d, 0x3d, 0xaa, 0x48, 0xd2, 0x66, 0xb3, 0x7f, 0x87, 0x4d,
	0x6e, 0x8a, 0x01, 0xe0, 0x35, 0x49, 0x24, 0x79, 0x9a, 0x9a, 0x1a, 0x57, 0xd1, 0xdd, 0x8a, 0x30,
	0x80, 0x9d, 0x93, 0x8c, 0xdb, 0x3f, 0x91, 0x67, 0xed, 0xee, 0xfe, 0x07, 0xf9, 0x78, 0x95, 0xe7,
	0x3f, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xe7, 0x2d, 0x13, 0x14, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LotusClient is the client API for Lotus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LotusClient interface {
	GetLotByID(ctx context.Context, in *Lot, opts ...grpc.CallOption) (*Lot, error)
	GetLots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Lots, error)
}

type lotusClient struct {
	cc *grpc.ClientConn
}

func NewLotusClient(cc *grpc.ClientConn) LotusClient {
	return &lotusClient{cc}
}

func (c *lotusClient) GetLotByID(ctx context.Context, in *Lot, opts ...grpc.CallOption) (*Lot, error) {
	out := new(Lot)
	err := c.cc.Invoke(ctx, "/backend.lotus/GetLotByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lotusClient) GetLots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Lots, error) {
	out := new(Lots)
	err := c.cc.Invoke(ctx, "/backend.lotus/GetLots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LotusServer is the server API for Lotus service.
type LotusServer interface {
	GetLotByID(context.Context, *Lot) (*Lot, error)
	GetLots(context.Context, *Empty) (*Lots, error)
}

func RegisterLotusServer(s *grpc.Server, srv LotusServer) {
	s.RegisterService(&_Lotus_serviceDesc, srv)
}

func _Lotus_GetLotByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Lot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotusServer).GetLotByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.lotus/GetLotByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotusServer).GetLotByID(ctx, req.(*Lot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lotus_GetLots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LotusServer).GetLots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.lotus/GetLots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LotusServer).GetLots(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Lotus_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.lotus",
	HandlerType: (*LotusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLotByID",
			Handler:    _Lotus_GetLotByID_Handler,
		},
		{
			MethodName: "GetLots",
			Handler:    _Lotus_GetLots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/lotus.proto",
}
